import { logout } from "@/actions/auth-action";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
    return <>
        <header className="py-4">
            <div className="flex column justify-between px-8">
                <p className="text-xl">Welcome Back!</p>
                <form action={logout}>
                    <button className="bg-blue-500 rounded-xl px-4 py-2">Logout</button>
                </form>
            </div>
        </header>
        {children}
    </>
}